name: todo
description: Flutter Todo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^3.4.5
  equatable: ^2.0.5
  firebase_app_check: ^0.0.6+20
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  firebase_storage: ^10.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.1
  get_it: ^7.2.0
  google_sign_in: ^5.4.1
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.6.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
