name: todo
description: Flutter Todo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^3.4.5
  firebase_app_check: ^0.0.6+20
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  firebase_storage: ^10.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
